spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/post
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true #logger가 아닌 시스템 로그에 찍는 것이므로 사용하지 않음
        format_sql: true
        default_batch_fetch_size: 100

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6